### ISSUE TITLE
projecting only one sample in smart_mva()

### ISSUE THREAD

**Issue by killidude** [ChristianHuber/smartsnp#7]
Hi Christian,

I believe there is a bug in smart_pca() function (and consequently the smart_mva()).

When I try to project only one individual onto the PCA space I get this error:

Projecting ancient samples onto PCA space
PCA space =PC1PC2PC3
Error in 1:sampN.anc : argument of length 0

This is independent of which individual I want to project, the dimensions of the PCA space, or how I compute the SVD.

If I project two or more individuals, everything runs as expected.

Projecting ancient samples onto PCA space
PCA space =PC1PC2PC3
Completed ancient sample projection
2 ancient samples projected

Thanks,

Tomas

**Comment by nevrome** [comment]
This commit is a minimal change to prevent this specific issue for `smart_pca()`: https://github.com/nevrome/smartsnp/commit/d15424f5fbb4e1c4aba9b6ef76d807c6f0e402b0

There might be more of these array indexing issues in the code, though.

**Comment by killidude** [comment]
@nevrome this looks like an easy fix. Hopefully @ChristianHuber will commit this patch to the master branch soon.

Thanks,

Tomas

**Comment by ChristianHuber** [comment]
Thanks, nevrome! I've added this patch to the master branch.
